### PR TITLE
fix incorrect named param for "Style"

### PR DESCRIPTION
**Pull request by exoad**
## Description

the name for the "List<StyleRule>" parameter was "rules" which does not align with the code which prompts for a named parameter called "styles"

## Type of Change

- [ ] ❌ Breaking change
- [ ] ✨ New feature or improvement
- [ ] 🛠️ Bug fix
- [ ] 🧹 Code refactor
- [X] 📝 Documentation
- [ ] 🗑️ Chore

## Ready Checklist

- [X] I've read the [Contribution Guide](https://github.com/schultek/jaspr/blob/main/CONTRIBUTING.md).
- [X] In case this PR changes one of the core packages, I've modified the respective **CHANGELOG.md** file using
      the [semantic_changelog](https://github.com/rrousselGit/semantic_changelog) format.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added myself to the AUTHORS file (optional, if you want to).

If you need help, consider asking for advice on the *#contribute* channel on [Discord](https://discord.gg/XGXrGEk4c6).

### CODE REVIEW

**Comment by exoad** [comment]
see https://github.com/schultek/jaspr/blob/098db73cc7bd28dd0c0d4361e8ce8b8a8a27fa30/packages/jaspr/lib/src/components/style.dart#L6

**Comment by cybertheory** [comment]
I think because it refers to the StyleRule object which is a <style> block, the Styles objects you are referring to are inline styles

**Comment by exoad** [comment]
> I think because it refers to the StyleRule object which is a <style> block, the Styles objects you are referring to are inline styles

Huh, I am referring to the documentation calling one of the parameters in the `Style` class's constructor incorrectly. 

In jaspr, it is:
https://github.com/schultek/jaspr/blob/098db73cc7bd28dd0c0d4361e8ce8b8a8a27fa30/packages/jaspr/lib/src/components/style.dart#L6

While the docs mention the construction of a `Style` object like this:

```dart
Style(rules: [
    StyleRule(
```

But it should be defined as 

```dart
Style(styles: [
```

Sorry for the confusion.

**Comment by cybertheory** [comment]
I get what you are saying, but why would styles be a better name than  rules? keep in mind that you can use MediaRules there as well.

These 'rules' are just the CSS rules within the style block not the actual Style block so it wouldn't make sense to call them 'styles'. 

Personally, I think at a low level calling them styles makes sense and if you want to abstract that away within your own projects you can!

**Comment by exoad** [comment]
> I get what you are saying, but why would styles be a better name than rules? keep in mind that you can use MediaRules there as well.
> 
> These 'rules' are just the CSS rules within the style block not the actual Style block so it wouldn't make sense to call them 'styles'.
> 
> Personally, I think at a low level calling them styles makes sense and if you want to abstract that away within your own projects you can!

I am saying the docs do not reflect the code...

**Comment by exoad** [comment]
It doesn't matter if the docs are called "rules," I am suggesting this PR in order to fix the naming error found in the code in conflict with the naming found in the quickstart guide.

**Comment by cybertheory** [comment]
Oh I see please disregard my previous comments then

**Comment by schultek** [comment]
Thanks.

**Pull request merged**
